import type { FC } from 'react';
import Head from 'next/head';
import styled from 'styled-components';

import PageContainer from 'components/atoms/PageContainer/PageContainer';

export interface LandingPageProps {}

const PageHeading = styled.h1`
  font-size: 48px;
  color: ${({ theme }) => theme.colors.primary[3]};
`;

const Landing: FC<LandingPageProps> = () => {
  return (
    <PageContainer>
      <Head>
        <title>StampIT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageHeading>StampIT</PageHeading>
    </PageContainer>
  );
};

export default Landing;
