import type { FC } from 'react';
import Head from 'next/head';

import PageContainer from 'components/atoms/PageContainer/PageContainer';
import styled from 'styled-components';
import GoBack from '../components/atoms/GoBack/GoBack';

export interface LandingPageProps {}

const Wrapper = styled.div`
  width: 75%;
  margin: 1rem auto 0 auto;
`;

const Heading = styled.h1`
  margin-top: 1rem;
`;

const Input = styled.input`
  background: #eee;
  border: 2px solid #eee;
  font-size: 1rem;
  font-family: inherit;
  padding: 0.2rem 0.4rem;
  border-radius: 0.25rem;
  transition: 0.2s all;
  outline: none;
  width: 4rem;
  margin: 0 auto;
  display: block;
  &:focus {
    border: 2px solid ${({ theme }) => theme.colors.gray};
  }
`;

const SettingLabel = styled.span`
  font-weight: bold;
`;

const SettingsGrid = styled.div`
  margin-top: 0.5rem;
  display: inline-grid;
  grid-template-columns: auto 1fr 1fr;

  span,
  div {
    padding: 0.5rem 1rem;
  }
`;

const SubHeading = styled.h4`
  margin-top: 1rem;
  font-size: 1.2rem;
`;

const SingleLengthSetting = ({ name }) => (
  <>
    <span>{name}</span>
    <div className="">
      <Input type="text" />
    </div>
    <div className="">
      <Input type="text" />
    </div>
  </>
);

const SettingsSection = () => (
  <div>
    <SubHeading>Sekcja adresat</SubHeading>
    <SettingsGrid>
      <SettingLabel>Nazwa pola</SettingLabel>
      <SettingLabel>Długość min</SettingLabel>
      <SettingLabel>Długość max</SettingLabel>
      <SingleLengthSetting name="Miejscowość" />
      <SingleLengthSetting name="Miejscowość" />
    </SettingsGrid>
  </div>
);

const SettingsPage: FC<LandingPageProps> = () => {
  return (
    <PageContainer wide>
      <Head>
        <title>Hack Yeah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <GoBack />
        <Heading>Ustawienia</Heading>
        <SettingsSection />
        <SettingsSection />
      </Wrapper>
    </PageContainer>
  );
};

export default SettingsPage;
