import type { FC } from 'react';
import Head from 'next/head';

import PageContainer from 'components/atoms/PageContainer/PageContainer';
import styled from 'styled-components';
import GoBack from '../components/atoms/GoBack/GoBack';

export interface LandingPageProps {}

const Wrapper = styled.div`
  width: 75%;
  margin: 1rem auto 0 auto;
`;

const Heading = styled.h1`
  margin-top: 1rem;
`;

const UserInfo = styled.div`
  line-height: 1.8rem;
  margin-top: 1rem;
`;

const UserProfilePage: FC<LandingPageProps> = () => {
  return (
    <PageContainer wide>
      <Head>
        <title>Hack Yeah</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
        <GoBack />
        <Heading>Profil użytkownika</Heading>
        <UserInfo>
          Nazwa użytkownika: admin <br />
          Imię: jan <br />
          Nazwisko: Kowalski <br />
        </UserInfo>
      </Wrapper>
    </PageContainer>
  );
};

export default UserProfilePage;
